services:
  api:
    build:
      context: .
      dockerfile: ./dockerfile
      target: Development
    container_name: passwordlisting_api
    ports:
      - "5063:5063"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=PasswordListingDb;User=postgres;Password=123456;
    depends_on:
      - db
    volumes:
      - ./PasswordListing:/src/PasswordListing
      - ./PasswordListing.Application:/src/PasswordListing.Application
      - ./PasswordListing.Infrastructure:/src/PasswordListing.Infrastructure
      - ./PasswordListing.Domain:/src/PasswordListing.Domain
  db:
    image: postgres:17-alpine
    container_name: passwordlisting_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=PasswordListingDb
    # volumes:
    #   - db_data:/var/lib/postgresql/data
# volumes:
#   db_data: