services:
  api:
    build:
      context: .
      dockerfile: ./dockerfile
      target: Development
    container_name: passwordlisting_api
    ports:
      - "5063:5063"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5063
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=PasswordListingDb;Username=postgres;Password=123456;
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/PasswordListing/bin
      - /app/PasswordListing/obj
      - /app/PasswordListing.Infrastructure/obj
      - /app/PasswordListing.Infrastructure/bin
      # - ./PasswordListing:/src/PasswordListing
      # - ./PasswordListing.Application:/src/PasswordListing.Application
      # - ./PasswordListing.Infrastructure:/src/PasswordListing.Infrastructure
      # - ./PasswordListing.Domain:/src/PasswordListing.Domain
      # - ~/.nuget/packages:/root/.nuget/packages:cached

    command: >
      sh -c "dotnet watch --project PasswordListing run --urls http://+:5063"
    #  dotnet restore --packages /root/.nuget/packages
    #  dotnet run --project PasswordListing --urls http://+:5063
    #  dotnet watch --project PasswordListing run --urls http://+:5063
  db:
    image: postgres:17-alpine
    container_name: passwordlisting_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=PasswordListingDb
    # volumes:
    #   - db_data:/var/lib/postgresql/data
# volumes:
#   db_data: